### ISSUE TITLE
Gulp with js modules and concat

### ISSUE THREAD

**Issue by dride-for-sure** [seancdavis/seancdavis-com#57]
### Description
In Part 2 https://www.seancdavis.com/blog/compile-es6-code-gulp-babel-part-2/ you suggest to `.pipe(concat())` before `.pipe(babel())`. In case of using es6 modules with import/export statements that is not possible. The bundled file then includes identifiers that gets declared before the intended declaration and because of this babel drops with an syntax error on _“Identifier ‘foo’ has already been declared"_.

_(example js file after `.pipe(concat())` and before `.pipe(babel())`)_
```javascript
import Foo from './bar';

const bar = new Foo();

export default class Foo {};
```
### Possible solution
Use another plugin (or do it on your own, prefered!) to regex out the import/export statements, then concat, then babel.

Btw.: Thanks for you enriching website. Keep going.

**Comment by seancdavis** [comment]
👋 Hi @dride-for-sure! Thank you for your help in submitting this issue. As I understand, this is a note I've received a few times, so I'm happy to go back and address.

After playing with it for a bit, I agree that your situation is a common one. However, it doesn't _really_ play well with this solution. Concatenating into a single file is kind of an old-school solution that seems unnecessary with the modern capabilities of ES6.

In order for imports to be effective within the scope of this post (Gulp + Babel), you'd have to bring over the files you want to import individually and import them on the fly. That feels messy. That starts to point me in the direction of a compiling tool like Webpack, Parcel, Rollup, etc.

What I'm thinking I should do here is:

- [ ] Add a post that covers your situation – an ES6 compiler example using one of these build tools along with Babel.
- [ ] Add commentary to the existing Part 2 Babel + Gulp article that a) notes the issue with imports and b) points to the other post.

**Comment by seancdavis** [comment]
See #216 for the snippet I added to Part 2.

---

More comments are welcome here. I didn't really feel it was worth the effort to open the can of worms that would be introducing webpack into the Gulp pipeline for these examples.

I realize that makes this approach a bit old school. It's also my opinion that Gulp, in general, is unnecessary with more modern tooling. For example, this site's build currently uses PostCSS + webpack + Eleventy and doesn't require a parent streaming service to wire it all together.
