### ISSUE TITLE
rake arguments blogpost seems to have broken code

### ISSUE THREAD

**Issue by vhermecz** [seancdavis/seancdavis-com#65]
Hey!
Wanted to write email, but seems like this is the way I found.

https://www.seancdavis.com/blog/4-ways-to-pass-arguments-to-a-rake-task/
https://github.com/seancdavis/seancdavis-com/blob/main/src/blog/posts/2014-12-13-4-ways-to-pass-arguments-to-a-rake-task.md

Pretty nice writeup, but turns out that using Rails 5.2.3 and Ruby 2.6.2, the OptionParse approach does not work at all. Overall, after trying to fix my code, I am just crying back good old Python and Click, this aspect of ruby/rails feels like programming in DBase...

So, just thought, I'd ping you about it, it's up to you if you want to fix the post or add a banner with a warning.

Cheers, V

**Comment by seancdavis** [comment]
Thanks for submitting this issue @vhermecz!

I dug in to see if I could fix it. I haven't worked with Ruby in awhile, but it was fun to get back in! (Thanks for the nudge.) It turns out there was a pretty simple fix. See #163 for the adjusments.
